INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('1','B', '.');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('2','B', '.');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('3','C', '.');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('4','B', '.');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('5','C', '.');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('6','C', '.');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('7','A', '.');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('8','D', '.');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('9','A', '.');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('10','B', '.');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('11','C', '.');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('12','D', '.');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('13','B', '.');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('14','B', '.');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('15','C', '.');

