INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('1','A', 'SADFHKJDSAF');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('2','B', 'SADFHKJDSAF');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('3','C', 'SADFHKJDSAF');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('4','D', 'SADFHKJDSAF');
INSERT INTO JUAN_GARCIA (NUMERO,LETRA, RESPUESTA) VALUES ('5','E', 'SADFHKJDSAF');


